#!/bin/sh
cd "${0%/*}" || exit # run from this directory

echo "Running blockMesh"
blockMesh > log.blockMesh

surfaceTransformPoints  -rotate-y $AOA constant/triSurface/def-morphWing.stl constant/triSurface/morphWingTran.stl > log.surfaceFeature

echo "Extracting Features"
surfaceFeatureExtract >> log.surfaceFeature

decomposePar > log.decomposePar

echo "Meshing"
mpirun -oversubscribe -n 4 snappyHexMesh -overwrite -parallel > log.snappyHexMesh

mpirun -oversubscribe -n 4 topoSet -parallel >> log.snappyHexMesh

echo "Creating 0 dirs"
rm -rf processor*/0
ls -d processor* | xargs -I{} cp -r 0.orig {}/0 

mpirun -oversubscribe -n 4 patchSummary -parallel > log.patchSummary

mpirun -oversubscribe -n 4 potentialFoam -writephi -parallel  > log.potentialFoam

echo "Checking Mesh"
mpirun -oversubscribe -n 4 checkMesh -parallel > log.checkMesh

echo "Running Solver"
export SOLVER_APP=$(foamDictionary -entry application -value system/controlDict) > /dev/null
mpirun -oversubscribe -n 4 $SOLVER_APP -parallel > log.solver

echo "making VTK for export"
mpirun -oversubscribe -n 4 foamToVTK -parallel -ascii -latestTime -overwrite -cellSet smallVolume

reconstructParMesh -constant > log.reconstruct

reconstructPar -latestTime >> log.reconstruct



echo "DONE"
