#!/bin/sh
cd "${0%/*}" || exit		# Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions	# Tutorial run functions

blockMesh

surfaceTransformPoints  -rotate-y $AOA  constant/triSurface/def-morphWing.stl constant/triSurface/morphWingTran.stl > log

surfaceFeatureExtract >> log

#decomposePar > log &

snappyHexMesh -overwrite > log.snappyHexMesh 

#runParallel snappyHexMesh -overwrite -use-hwthread-cpus 

cp -r 0.orig 0

patchSummary  > log.patchSummary 

potentialFoam -writephi > log.potentialFoam  

checkMesh > log.checkMesh 

$(getApplication) > log.solver

#runApplication reconstructParMesh -constant 

#runApplication reconstructPar -latestTime
